namespace Bet.Extensions.Walmart.Models;

public enum OrderCancelEnum
{
    CUSTOMER_REQUESTED_SELLER_TO_CANCEL,
    SELLER_CANCEL_PRICING_ERROR,
    SELLER_CANCEL_OUT_OF_STOCK,
    SELLER_CANCEL_FRAUD_STOP_SHIPMENT,
    SELLER_CANCEL_ADDRESS_NOT_SERVICEABLE
}
